### ISSUE TITLE
Wrong number of arguments Rails 5, 0.0.3 + administrate 0.15.0 

### ISSUE THREAD

**Issue by airjoshb** [apsislabs/administrate-field-acts_as_taggable#5]
I'm getting an error after upgrading Administrate to 0.15.0

`ArgumentError: wrong number of arguments (given 2, expected 1)
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/administrate-field-acts_as_taggable-0.0.3/lib/administrate/field/acts_as_taggable.rb:24:in `permitted_attribute'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/administrate-0.15.0/lib/administrate/field/deferred.rb:52:in `permitted_attribute'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/administrate-0.15.0/lib/administrate/base_dashboard.rb:59:in `block in permitted_attributes'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/administrate-0.15.0/lib/administrate/base_dashboard.rb:58:in `map'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/administrate-0.15.0/lib/administrate/base_dashboard.rb:58:in `permitted_attributes'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/administrate-0.15.0/app/controllers/administrate/application_controller.rb:154:in `resource_params'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/administrate-0.15.0/app/controllers/administrate/application_controller.rb:61:in `update'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/actionpack-5.0.7.2/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/actionpack-5.0.7.2/lib/abstract_controller/base.rb:188:in `process_action'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/actionpack-5.0.7.2/lib/action_controller/metal/rendering.rb:30:in `process_action'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/actionpack-5.0.7.2/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:126:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:455:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:90:in `run_callbacks'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/actionpack-5.0.7.2/lib/abstract_controller/callbacks.rb:19:in `process_action'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/actionpack-5.0.7.2/lib/action_controller/metal/rescue.rb:20:in `process_action'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/actionpack-5.0.7.2/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/notifications.rb:164:in `block in instrument'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/notifications.rb:164:in `instrument'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/actionpack-5.0.7.2/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/actionpack-5.0.7.2/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/activerecord-5.0.7.2/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/actionpack-5.0.7.2/lib/abstract_controller/base.rb:126:in `process'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/actionview-5.0.7.2/lib/action_view/rendering.rb:30:in `process'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/actionpack-5.0.7.2/lib/action_controller/metal.rb:190:in `dispatch'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/actionpack-5.0.7.2/lib/action_controller/metal.rb:262:in `dispatch'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/actionpack-5.0.7.2/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/actionpack-5.0.7.2/lib/action_dispatch/routing/route_set.rb:32:in `serve'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/actionpack-5.0.7.2/lib/action_dispatch/journey/router.rb:39:in `block in serve'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/actionpack-5.0.7.2/lib/action_dispatch/journey/router.rb:26:in `each'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/actionpack-5.0.7.2/lib/action_dispatch/journey/router.rb:26:in `serve'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/actionpack-5.0.7.2/lib/action_dispatch/routing/route_set.rb:727:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/rack-attack-6.5.0/lib/rack/attack.rb:113:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/newrelic_rpm-6.15.0/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/newrelic_rpm-6.15.0/lib/new_relic/rack/browser_monitoring.rb:33:in `traced_call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:40:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/cookies.rb:613:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/activerecord-5.0.7.2/lib/active_record/migration.rb:553:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:90:in `run_callbacks'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/callbacks.rb:36:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/executor.rb:12:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/web-console-2.3.0/lib/web_console/middleware.rb:28:in `block in call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/web-console-2.3.0/lib/web_console/middleware.rb:18:in `catch'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/web-console-2.3.0/lib/web_console/middleware.rb:18:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/railties-5.0.7.2/lib/rails/rack/logger.rb:36:in `call_app'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/railties-5.0.7.2/lib/rails/rack/logger.rb:24:in `block in call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/tagged_logging.rb:69:in `block in tagged'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/tagged_logging.rb:26:in `tagged'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/tagged_logging.rb:69:in `tagged'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/railties-5.0.7.2/lib/rails/rack/logger.rb:24:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/sprockets-rails-3.2.2/lib/sprockets/rails/quiet_assets.rb:13:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/request_id.rb:24:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/executor.rb:12:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/static.rb:136:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/railties-5.0.7.2/lib/rails/engine.rb:522:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/rack-2.2.3/lib/rack/handler/webrick.rb:95:in `service'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/2.4.0/webrick/httpserver.rb:140:in `service'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/2.4.0/webrick/httpserver.rb:96:in `run'
	from /Users/joshua/.rbenv/versions/2.4.5/lib/ruby/2.4.0/webrick/server.rb:308:in `block in start_thread'`

I've got a pretty standard set up with acts_as_taggable_on :tags

I've spent a bunch of time searching around and any help would be great.

**Comment by Allanon29** [comment]
I can confirm that the same error occurs in Rails 6 as well.

**Comment by andreibondarev** [comment]
This issue should be fixed here: https://github.com/apsislabs/administrate-field-acts_as_taggable/pull/6
